### ISSUE TITLE
MacOS Mojave: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by yaofei-li** [OpenSourceRisk/Engine#38]
Hi, I am trying to install ORE on my MacOS Mojave, but got some troubles. Firstly, when I tried to built "App", the compilation was ended by the error "ld: symbol(s) not found for architecture x86_64". The detailed output of "make -j4" is provided in the file "output_make"; just in case, I also attached the output of "./configure" below. After several hours spent on this issue, I just cannot solve it. Could please help me to figure out the problem? 

On the other hand, I am also not 100% sure whether the installation of QuantExt, OREData and OREAnalystics is fully successful. In fact, the compilation for all three doesn't show any error; so I guess it works and continue the next step. However, when I tried to test the installation, the "test-suite" file doesn't exist in their corresponding test file in each of the three; is that because the command "make -j4" didn't fully work? I am really confusing about this and doubt a lot whether the installation is truly accomplished. I do appreciate any support from your side and hopefully we can solve the issue to make ORE running on my computer. 

[output_.:configure.pdf](https://github.com/OpenSourceRisk/Engine/files/3170999/output_.configure.pdf)

[output_make.pdf](https://github.com/OpenSourceRisk/Engine/files/3170994/output_make.pdf)

**Comment by yaofei-li** [comment]
Hi, I bring some update here. In brief, I succeeded in installing ORE on my older MacBook Pro; the corresponding configurations are MacOS High Sierra Version 10.13.6, Command Line Tools macOS 10.13 for Xcode 9, Boost 1.67.0 and QuantLib 1.14. 

After searching a lot the error "ld: symbol(s) not found for architecture x86_64", I came across occasionally the link below
[https://github.com/ContinuumIO/anaconda-issues/issues/9096](url)

In the post, the person, who used exactly the same compiler with me, started to faced the same error soon after an update of Xcode to 9.3. And the compilation works fine for him on another computer with Xcode 9.0. **So I guessed the error should has something to do with the Command Line Tools** (as I didn't install things other than the Command Line Tools package for Xcode). 

To test this hypothesis, I tried to re-install the earliest version of Command Line Tools working for the MacOS Mojave. Unfortunately, the same error appeared again. Then I grabbed my older computer with the configuration listed in the beginning and re-installed also the oldest possible version; it's for Xcode 9. Magically, the ORE installation just worked perfectly: all test-suite files ran well and no errors were detected. On the other hand, I ran the example 1 to 3 and they worked too. So, at this stage, it seems that the installation was successful and the original error is strongly linked to the new version of Command Line Tools. Honestly, I don't have the suitable skill set to fix this error by my own. If possible, could you please try to solve it for the MacOS Mojave (10.14.5 now) with the newest Command Line Tools? As I did a lot of configurations for other purposes on my current computer and the older one mainly serves for entertainment now, it's not meaningful to get back to the older computer with older version just for running one program. 

For someone having the same issue with me, my personal advice is to manually configure the Boost and QuantLib at first place ("brew install boost/quantlib" doesn't work for me to install ORE). Then, if it still doesn't work, please take an attempt for downgrading your Command Line Tools to the oldest possible version for your current MacOS system. On the other hand, I largely referred to the issue #29; for the recent version of MacOS, you need to add cxxflags and ldflags behind "./configure". Hope this helps.

**Comment by pcaspers** [comment]
@yaofei-li can this bd closed?

**Comment by QuaternionRisk** [comment]
Hi Yaofei, I assume this can be closed. Please open a new issue when necessary.
