### ISSUE TITLE
Issues with Example_13

### ISSUE THREAD

**Issue by byouness** [OpenSourceRisk/Engine#8]
Hello,
Not sure if this is the right place to post this (let me know if I should move it to Stackoverflow or elsewhere). I just installed the ORE and compiled everything successfully (Visual Studio 2013 (in x64) with QuantLib-1.9.2 and boost_1_63_0), the first examples work fine but Example_13 doesn't, I get the following errors in the logs:
```
ALERT    [2017-Apr-20 17:37:50.956801] (...tfolio\portfolio.cpp:114) : Error building trade (Swap_2) : Expected a leg of coupons of type CappedFlooredIborCoupon
ALERT    [2017-Apr-20 17:38:21.997905] (...tfolio\portfolio.cpp:114) : Error building trade (Swap_2) : did not find object EUR of type capfloor curve under configuration libor
ALERT    [2017-Apr-20 17:38:22.609966] (orea\app\oreapp.cpp:147)     : Error: InMemoryCube::InMemoryCube no ids specified
```
I didn't change anything before running the example, so is it normal?
Thanks!

**Comment by QuaternionRisk** [comment]
Hi, did you compile on tag v1.8.0.7 or maybe on the current master? The latter is not guaranteed to work. Best Regards.

**Comment by byouness** [comment]
Hello, I compiled on the current master indeed. I will try the v1.8.0.7.
Thanks!
